// PelvisCollisionDetection.h: 标准系统包含文件的包含文件
// 或项目特定的包含文件。

#pragma once
#include "FileToMatrix.h"
#include "CollisionCallback.h"
#include "collisionDetect.h"

#include <iostream>
#include <iostream>
#include <vtkActor.h>
#include <vtkOBBTree.h>
#include "vtkTransform.h"
#include <vtkCallbackCommand.h>
#include <vtkCommand.h>
#include <vtkSliderRepresentation2D.h>
#include <vtkSliderWidget.h>
#include <vtkTextActor.h>
#include <vtkInteractorStyleTrackballCamera.h>
#include <vtkPointSource.h>
#include <vtkPolyData.h>
#include <vtkPolyDataMapper.h>
#include <vtkProperty.h>
#include <vtkProperty2D.h>
#include <vtkRenderWindow.h>
#include <vtkRenderWindowInteractor.h>
#include <vtkRenderer.h>
#include <vtkSliderRepresentation2D.h>
#include <vtkSliderWidget.h>
#include <vtkSmartPointer.h>
#include <vtkSphereSource.h>
#include <vtkTextProperty.h>
#include <vtkWidgetEvent.h>
#include <vtkWidgetEventTranslator.h>
#include <vtkRenderer.h>
#include <vtkBYUReader.h>
#include <vtkOBJReader.h>
#include <vtkPLYReader.h>
#include <vtkPolyDataReader.h>
#include <vtkSTLReader.h>
#include <vtkXMLPolyDataReader.h>
#include <vtkCamera.h>
#include <vtkMath.h>
#include <vtkNamedColors.h>
#include <chrono>
#include <sstream>
#include <string>
#include <thread>
#include <vtkConeSource.h>
#include <vtkOBBTree.h>
#include <vtkLinearTransform.h>
#include <vtkTransform.h>
#include <vtkAxesActor.h>
#include <vtksys/SystemTools.hxx>
#include <vtkTransformPolyDataFilter.h>
#include <time.h>
#include <vtkMatrix4x4.h>
#include <vtkCommand.h>
#include <vtkTransformPolyDataFilter.h>
#include <vtkTransformInterpolator.h>
#include "collisionDetect.h"
#include <vtkSmartPointer.h>
#include <vtkCallbackCommand.h>
#include <vtkPropPicker.h>
#include <vtkInteractorStyleTrackballActor.h>

// TODO: 在此处引用程序需要的其他标头。
